INSERT INTO PUBLIC.RESTAURANT (ID, NAME, PHONE, ADDRESS, NOTE, EMAIL, TIME_WORK, CREATE_DATE, MODIFIED_DATE) VALUES (1, 'test', 'test', 'test', 'test', 'test@test.test', 'test', '2019-03-26 13:26:38.112000000', '2019-03-26 13:26:40.094000000');
INSERT INTO PUBLIC.RESTAURANT (ID, NAME, PHONE, ADDRESS, NOTE, EMAIL, TIME_WORK, CREATE_DATE, MODIFIED_DATE) VALUES (8, 'testWithMenu', 'testPhone', 'testAddress', 'testNote', 'testEmail', 'testTimeWork', null, null);
INSERT INTO PUBLIC.RESTAURANT (ID, NAME, PHONE, ADDRESS, NOTE, EMAIL, TIME_WORK, CREATE_DATE, MODIFIED_DATE) VALUES (9, 'testName', 'testPhone', 'testAddress', 'testNote', 'testEmail', 'testTimeWork', null, null);
INSERT INTO PUBLIC.RESTAURANT (ID, NAME, PHONE, ADDRESS, NOTE, EMAIL, TIME_WORK, CREATE_DATE, MODIFIED_DATE) VALUES (13, 'testName', 'testPhone', 'testAddress', 'testNote', 'testEmail', 'testTimeWork', null, null);
INSERT INTO PUBLIC.RESTAURANT (ID, NAME, PHONE, ADDRESS, NOTE, EMAIL, TIME_WORK, CREATE_DATE, MODIFIED_DATE) VALUES (17, 'testName', 'testPhone', 'testAddress', 'testNote', 'testEmail', 'testTimeWork', null, null);


INSERT INTO PUBLIC.MENU (ID, NAME, NOTE, PHOTO_SRC, DATE_MENU, RESTAURANT_ID, CREATE_DATE, MODIFY_DATE, MODIFIED_DATE) VALUES (3, 'punct_menu1', '8', '', '2019-04-17', 8, null, null, null);
INSERT INTO PUBLIC.MENU (ID, NAME, NOTE, PHOTO_SRC, DATE_MENU, RESTAURANT_ID, CREATE_DATE, MODIFY_DATE, MODIFIED_DATE) VALUES (4, 'punct_menu2', '8', '', '2019-04-17', 8, null, null, null);
INSERT INTO PUBLIC.MENU (ID, NAME, NOTE, PHOTO_SRC, DATE_MENU, RESTAURANT_ID, CREATE_DATE, MODIFY_DATE, MODIFIED_DATE) VALUES (5, 'punct_menu3', '9', '', '2019-04-17', 9, null, null, null);
INSERT INTO PUBLIC.MENU (ID, NAME, NOTE, PHOTO_SRC, DATE_MENU, RESTAURANT_ID, CREATE_DATE, MODIFY_DATE, MODIFIED_DATE) VALUES (6, 'punct_menu4', '9', '', '2019-04-17', 9, null, null, null);
INSERT INTO PUBLIC.MENU (ID, NAME, NOTE, PHOTO_SRC, DATE_MENU, RESTAURANT_ID, CREATE_DATE, MODIFY_DATE, MODIFIED_DATE) VALUES (7, 'punct_menu5', '13', '', '2019-04-17', 13, null, null, null);
INSERT INTO PUBLIC.MENU (ID, NAME, NOTE, PHOTO_SRC, DATE_MENU, RESTAURANT_ID, CREATE_DATE, MODIFY_DATE, MODIFIED_DATE) VALUES (8, 'punct_menu6', '13', '', '2019-04-17', 13, null, null, null);
INSERT INTO PUBLIC.MENU (ID, NAME, NOTE, PHOTO_SRC, DATE_MENU, RESTAURANT_ID, CREATE_DATE, MODIFY_DATE, MODIFIED_DATE) VALUES (9, 'punct_menu7', '17', '', '2019-04-17', 17, null, null, null);
INSERT INTO PUBLIC.MENU (ID, NAME, NOTE, PHOTO_SRC, DATE_MENU, RESTAURANT_ID, CREATE_DATE, MODIFY_DATE, MODIFIED_DATE) VALUES (2, '2323', '23', null, '2019-04-17', 1, null, null, null);
INSERT INTO PUBLIC.MENU (ID, NAME, NOTE, PHOTO_SRC, DATE_MENU, RESTAURANT_ID, CREATE_DATE, MODIFY_DATE, MODIFIED_DATE) VALUES (1, 'test', 'test', 'test_src', '2019-04-17', 1, '2019-03-26 13:28:30.100000000', '2019-03-26 13:28:34.792000000', null);

INSERT INTO PUBLIC.USER (ID, LOGIN, PASSWORD, FIRST_NAME, LAST_NAME, PATRONYMIC, CREATE_DATE, MODIFIED_DATE, SECURITY_ROLE_ID) VALUES (1, 'test', 'test', 'test', 'test', 'test', '2019-03-26 13:25:51.584000000', '2019-03-26 13:25:55.556000000', null);
INSERT INTO PUBLIC.USER (ID, LOGIN, PASSWORD, FIRST_NAME, LAST_NAME, PATRONYMIC, CREATE_DATE, MODIFIED_DATE, SECURITY_ROLE_ID) VALUES (2, 'I', 'passwd', 'Smersh', 'Last', 'Patronymic', null, null, 0);
INSERT INTO PUBLIC.USER (ID, LOGIN, PASSWORD, FIRST_NAME, LAST_NAME, PATRONYMIC, CREATE_DATE, MODIFIED_DATE, SECURITY_ROLE_ID) VALUES (3, 'admin', 'passwd', 'Admin', 'Last', 'Patronymic', null, null, 0);
INSERT INTO PUBLIC.USER (ID, LOGIN, PASSWORD, FIRST_NAME, LAST_NAME, PATRONYMIC, CREATE_DATE, MODIFIED_DATE, SECURITY_ROLE_ID) VALUES (4, 'user1', 'passwd', 'User1', 'Last', 'Patronymic', null, null, 2);
INSERT INTO PUBLIC.USER (ID, LOGIN, PASSWORD, FIRST_NAME, LAST_NAME, PATRONYMIC, CREATE_DATE, MODIFIED_DATE, SECURITY_ROLE_ID) VALUES (5, 'user2', 'passwd', 'User2', 'Last', 'Patronymic', null, null, 2);
INSERT INTO PUBLIC.USER (ID, LOGIN, PASSWORD, FIRST_NAME, LAST_NAME, PATRONYMIC, CREATE_DATE, MODIFIED_DATE, SECURITY_ROLE_ID) VALUES (6, 'user3', 'passwd', 'User3', 'Last', 'Patronymic', null, null, 2);
INSERT INTO PUBLIC.USER (ID, LOGIN, PASSWORD, FIRST_NAME, LAST_NAME, PATRONYMIC, CREATE_DATE, MODIFIED_DATE, SECURITY_ROLE_ID) VALUES (7, 'user4', 'passwd', 'User4', 'Last', 'Patronymic', null, null, 2);
INSERT INTO PUBLIC.USER (ID, LOGIN, PASSWORD, FIRST_NAME, LAST_NAME, PATRONYMIC, CREATE_DATE, MODIFIED_DATE, SECURITY_ROLE_ID) VALUES (13, 'user10', 'passwd', 'User10', 'Last', 'Patronymic', null, null, 2);
INSERT INTO PUBLIC.USER (ID, LOGIN, PASSWORD, FIRST_NAME, LAST_NAME, PATRONYMIC, CREATE_DATE, MODIFIED_DATE, SECURITY_ROLE_ID) VALUES (9, 'user6', 'passwd', 'User6', 'Last', 'Patronymic', null, null, 2);
INSERT INTO PUBLIC.USER (ID, LOGIN, PASSWORD, FIRST_NAME, LAST_NAME, PATRONYMIC, CREATE_DATE, MODIFIED_DATE, SECURITY_ROLE_ID) VALUES (8, 'user5', 'passwd', 'User5', 'Last', 'Patronymic', null, null, 2);
INSERT INTO PUBLIC.USER (ID, LOGIN, PASSWORD, FIRST_NAME, LAST_NAME, PATRONYMIC, CREATE_DATE, MODIFIED_DATE, SECURITY_ROLE_ID) VALUES (11, 'user8', 'passwd', 'User8', 'Last', 'Patronymic', null, null, 2);
INSERT INTO PUBLIC.USER (ID, LOGIN, PASSWORD, FIRST_NAME, LAST_NAME, PATRONYMIC, CREATE_DATE, MODIFIED_DATE, SECURITY_ROLE_ID) VALUES (10, 'user7', 'passwd', 'User7', 'Last', 'Patronymic', null, null, 2);
INSERT INTO PUBLIC.USER (ID, LOGIN, PASSWORD, FIRST_NAME, LAST_NAME, PATRONYMIC, CREATE_DATE, MODIFIED_DATE, SECURITY_ROLE_ID) VALUES (12, 'user9', 'passwd', 'User9', 'Last', 'Patronymic', null, null, 2);

INSERT INTO PUBLIC.VOTING (ID, RESTAURANT_ID, USER_ID, CREATE_DATE, MODIFIED_DATE, REPORT_DATE) VALUES (1, 9, 1, null, null, '2019-04-26');